<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="LoginTCSuite" duration-ms="22305" started-at="2021-02-19T16:43:59Z" finished-at="2021-02-19T16:44:21Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="22305" started-at="2021-02-19T16:43:59Z" finished-at="2021-02-19T16:44:21Z">
      <class name="com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest">
        <test-method status="PASS" signature="setup(java.lang.String, java.lang.String)[pri:0, instance:com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest@222afc67]" name="setup" is-config="true" duration-ms="11357" started-at="2021-02-19T22:13:59Z" finished-at="2021-02-19T22:14:10Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[chrome]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[qa]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="TC01_FailedLoginTest()[pri:0, instance:com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest@222afc67]" name="TC01_FailedLoginTest" duration-ms="3550" started-at="2021-02-19T22:14:10Z" finished-at="2021-02-19T22:14:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC01_FailedLoginTest -->
        <test-method status="FAIL" signature="TC02_FailedLoginTest()[pri:0, instance:com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest@222afc67]" name="TC02_FailedLoginTest" duration-ms="1183" started-at="2021-02-19T22:14:14Z" finished-at="2021-02-19T22:14:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Not matched expected [Invalid] but found [Invalid credentials]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Not matched expected [Invalid] but found [Invalid credentials]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at org.testng.Assert.assertEquals(Assert.java:176)
	at com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest.TC02_FailedLoginTest(TC_LoginTest.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
	at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
	at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
	at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC02_FailedLoginTest -->
        <test-method status="PASS" signature="TC03_SuccessLoginTest()[pri:0, instance:com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest@222afc67]" name="TC03_SuccessLoginTest" duration-ms="5523" started-at="2021-02-19T22:14:16Z" finished-at="2021-02-19T22:14:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC03_SuccessLoginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest@222afc67]" name="tearDown" is-config="true" duration-ms="210" started-at="2021-02-19T22:14:21Z" finished-at="2021-02-19T22:14:21Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- LoginTCSuite -->
</testng-results>
