<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-D34DC2QJ" name="Test" tests="3" failures="1" timestamp="19 Feb 2021 16:44:22 GMT" time="22.305" errors="0">
  <testcase name="TC01_FailedLoginTest" time="3.55" classname="com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest"/>
  <testcase name="TC02_FailedLoginTest" time="1.183" classname="com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest">
    <failure type="java.lang.AssertionError" message="Not matched expected [Invalid] but found [Invalid credentials]">
      <![CDATA[java.lang.AssertionError: Not matched expected [Invalid] but found [Invalid credentials]
	at com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest.TC02_FailedLoginTest(TC_LoginTest.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- TC02_FailedLoginTest -->
  <testcase name="TC03_SuccessLoginTest" time="5.523" classname="com.BusyQA.UITest.TestCases.Sprint1.TC_LoginTest"/>
</testsuite> <!-- Test -->
